#!/usr/bin/env python3

import os
import sys


try:
    day = int(sys.argv[1])
except (IndexError, ValueError):
    print(f"Usage:\n\n    {sys.argv[0]} DAY\n")
    print(f"where DAY is an integer (i.e. 1 or 10).")
    exit(1)

if os.path.isfile(f"python/day{day:02d}.py"):
    print("Using Python script:")
    os.system(f"python3 python/day{day:02d}.py")

if os.path.isfile(f"ocaml/day{day:02d}.ml"):
    print("\nUsing OCaml script:")
    os.system(f"dune exec ocaml/day{day:02d}.exe")
